max_loop_distance: 2.0 # Maximum distance between two nodes in a loop
synthetic_graph_gen_iterations: 1 # Number of iterations to generate a synthetic graph
seed_graph_depth: 10 # Depth of the seed graph