hidden_size: 512 # Hidden size of the encoder and decoder GRU
num_layers: 4 # Number of layers of the encoder and decoder GRU
embedding_size: 256 # Size of the embedding vector
is_bidirectional: true # If true, the encoder and decoder are bidirectional
